colors:
  # Original "catppuccin" theme
  # https://github.com/catppuccin/catppuccin

  rosewater: "f5e0dc"
  flamingo: "f2cdcd"
  pink: "f5c2e7"
  mauve: "cba6f7"
  red: "f38ba8"
  maroon: "eba0ac"
  peach: "fab387"
  yellow: "f9e2af"
  green: "a6e3a1"
  teal: "94e2d5"
  sky: "89dceb"
  sapphire: "74c7ec"
  blue: "89b4fa"
  lavender: "b4befe"

  text: "cdd6f4"
  subtext1: "bac2de"
  subtext0: "a6adc8"
  overlay2: "9399b2"
  overlay1: "7f849c"
  overlay0: "6c7086"
  surface2: "585b70"
  surface1: "45475a"
  surface0: "313244"

  base: "1e1e2e"
  mantle: "181825"
  crust: "11111b"

core:
  normal_text:
    foreground: subtext1
  regular_file: {}
  reset_to_normal:
    foreground: subtext1

  directory:
    foreground: blue
    font-style: bold

  symlink:
    foreground: sky

  broken_symlink:
    foreground: mantle
    background: red
    font-style: bold

  missing_symlink_target:
    foreground: red
    font-style: bold

  multi_hard_link: {}

  fifo:
    foreground: crust
    background: blue

  socket:
    foreground: crust
    background: pink

  door:
    foreground: crust
    background: pink

  block_device:
    foreground: sapphire
    background: surface0

  character_device:
    foreground: pink
    background: surface0

  setuid:
    foreground: subtext0

  setgid:
    foreground: subtext0

  file_with_capability:
    foreground: subtext1

  sticky_other_writable:
    foreground: base
    background: sky
    font-style: bold

  other_writable:
    foreground: sky
    background: overlay2
    font-style: bold

  sticky:
    foreground: overlay2

  executable_file:
    foreground: green
    font-style: bold

text:
  foreground: text
  special:
    foreground: lavender
    font-style: bold
  todo:
    foreground: pink
    font-style: bold
  licenses:
    foreground: overlay1
  configuration:
    foreground: peach
    font-style: bold
    dockerfile:
      foreground: sky

markup:
  foreground: text

programming:
  foreground: yellow
  source:
    foreground: yellow
    font-style: bold
  tooling:
    foreground: sapphire
    font-style: bold
    continuous-integration:
      foreground: sapphire
      font-style: italic

media:
  foreground: mauve
  audio:
    foreground: yellow
    font-style: italic
  image:
    foreground: mauve
    font-style: bold
  video:
    foreground: text
    font-style: bold
  fonts:
    foreground: subtext1
    font-style: bold

office:
  foreground: red

archives:
  foreground: maroon
  font-style: bold

executable:
  foreground: green
  font-style: bold

unimportant:
  foreground: overlay0
